spring.application.name=odontocore.crm
spring.config.import=optional:application-local.properties

# Configurações do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/odontocoredb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Log de transações
logging.level.org.springframework.transaction=DEBUG

# JWT configuração
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
