spring.application.name=odontocore.crm

# Configurações do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/odontocoredb?currentSchema=crm_db
spring.datasource.username=postgres
spring.datasource.password=odontodb123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Log de transações
logging.level.org.springframework.transaction=DEBUG